services:
  orchestrator:
    build:
      context: ../packages/orchestrator
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CATALYST_GQL_GATEWAY_ENDPOINT=ws://gateway:4000/api
      - PORT=3000
    depends_on:
      - gateway

  gateway:
    build:
      context: ../packages/gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - books-service
      - movies-service

  books-service:
    build:
      context: ../packages/examples
      dockerfile: Dockerfile.books
    ports:
      - "8081:8080"
    environment:
      - PORT=8080

  movies-service:
    build:
      context: ../packages/examples
      dockerfile: Dockerfile.movies
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
